from enum import StrEnum


class WorkflowState(StrEnum):
    """Valid states for the data science workflow."""

    PROBLEM_FRAMING = "PROBLEM_FRAMING"
    AWAITING_PROBLEM_APPROVAL = "AWAITING_PROBLEM_APPROVAL"

    DATA_UNDERSTANDING = "DATA_UNDERSTANDING"
    AWAITING_DATA_APPROVAL = "AWAITING_DATA_APPROVAL"

    DATA_PREPARATION = "DATA_PREPARATION"
    AWAITING_PREPARATION_APPROVAL = "AWAITING_PREPARATION_APPROVAL"

    MODELING = "MODELING"
    AWAITING_MODEL_SELECTION = "AWAITING_MODEL_SELECTION"

    EVALUATION = "EVALUATION"
    AWAITING_GO_NO_GO = "AWAITING_GO_NO_GO"

    FINALIZATION = "FINALIZATION"
    AWAITING_HANDOFF_APPROVAL = "AWAITING_HANDOFF_APPROVAL"

    BLOCKED = "BLOCKED"
    COMPLETE = "COMPLETE"
